version: '3.9'

services:
  backend:
    build:
      context: ./app/backend
    container_name: django_backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/backend:/usr/src/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      mysql_db:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./app/frontend
    container_name: react_frontend
    command: sh -c "npm install && npm start"
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  mysql_db:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ubuntu
      MYSQL_DATABASE: db_gestion_rv
      MYSQL_USER: anta
      MYSQL_PASSWORD: ubuntu
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
