# Generated by Django 5.0.1 on 2025-01-29 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


from django.db import migrations

def set_default_status(apps, schema_editor):
    Appointment = apps.get_model('appointments', 'Appointment')
    Appointment.objects.filter(status__isnull=True).update(status='active')

class Migration(migrations.Migration):
    dependencies = [
        ('appointments', 'previous_migration'),
    ]

    operations = [
        migrations.RunPython(set_default_status),
    ]

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
