# Generated by Django 5.0.1 on 2025-01-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'get_latest_by': 'date'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
