# Generated by Django 5.0.1 on 2025-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_type_alter_appointment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé'), ('past', 'Passé')], default='active', max_length=10),
        ),
    ]
