# Generated by Django 5.0.1 on 2025-02-01 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_canceledappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceledappointment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='canceledappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
