# Generated by Django 5.0.1 on 2025-02-01 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_canceledappointment_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canceledappointment',
            options={},
        ),
        migrations.RemoveField(
            model_name='canceledappointment',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='canceledappointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='canceledappointment',
            name='original_date',
        ),
        migrations.RemoveField(
            model_name='canceledappointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='canceledappointment',
            name='reason',
        ),
        migrations.AddField(
            model_name='canceledappointment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.appointment'),
        ),
        migrations.AddField(
            model_name='canceledappointment',
            name='canceled_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
