# Generated by Django 5.0.1 on 2025-02-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
