# Generated by Django 5.0.1 on 2025-02-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appointment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canceledappointment',
            old_name='canceled_at',
            new_name='cancelled_at',
        ),
    ]
