# Generated by Django 5.0.1 on 2025-02-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_canceled_at_canceledappointment_cancelled_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canceledappointment',
            old_name='cancelled_at',
            new_name='canceled_at',
        ),
    ]
