# Generated by Django 5.0.1 on 2025-02-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_cancelled_at_canceledappointment_canceled_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canceledappointment',
            old_name='canceled_at',
            new_name='cancelled_at',
        ),
    ]
