# Generated by Django 5.0.1 on 2025-02-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_canceled_at_canceledappointment_cancelled_at'),
    ]

    operations = [
    ]
